packages:
  - apps/*
  - packages/*
  - tooling/*

catalogMode: manual

catalog:
  '@t3-oss/env-core': ^0.13.11
  '@tsconfig/strictest': ^2.0.8
  '@types/node': ^20.19.43
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  better-auth: 1.7.0-rc.1
  drizzle-orm: 1.0.0-rc.4
  drizzle-kit: 1.0.0-rc.4
  react: ^19.2.7
  react-dom: ^19.2.7
  postgres: 3.4.9
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
  zod: ^4.4.3

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'

allowBuilds:
  '@sentry/cli': false
  esbuild: false
