packages:
  - apps/*
  - packages/*
  - tooling/*

catalogMode: manual

catalog:
  '@t3-oss/env-core': ^0.13.11
  '@tsconfig/strictest': ^2.0.8
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
  zod: ^4.4.3

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'

allowBuilds:
  esbuild: false
