/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as authLayoutRouteImport } from './routes/(auth)/_layout'
import { Route as authLayoutSignupRouteImport } from './routes/(auth)/_layout.signup'
import { Route as authLayoutResetPasswordRouteImport } from './routes/(auth)/_layout.reset-password'
import { Route as authLayoutLoginRouteImport } from './routes/(auth)/_layout.login'
import { Route as authLayoutForgotPasswordRouteImport } from './routes/(auth)/_layout.forgot-password'

const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutSignupRoute = authLayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutResetPasswordRoute = authLayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutLoginRoute = authLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutForgotPasswordRoute =
  authLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof dashboardIndexRoute
  '/forgot-password': typeof authLayoutForgotPasswordRoute
  '/login': typeof authLayoutLoginRoute
  '/reset-password': typeof authLayoutResetPasswordRoute
  '/signup': typeof authLayoutSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof dashboardIndexRoute
  '/forgot-password': typeof authLayoutForgotPasswordRoute
  '/login': typeof authLayoutLoginRoute
  '/reset-password': typeof authLayoutResetPasswordRoute
  '/signup': typeof authLayoutSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(auth)/_layout': typeof authLayoutRouteWithChildren
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(auth)/_layout/forgot-password': typeof authLayoutForgotPasswordRoute
  '/(auth)/_layout/login': typeof authLayoutLoginRoute
  '/(auth)/_layout/reset-password': typeof authLayoutResetPasswordRoute
  '/(auth)/_layout/signup': typeof authLayoutSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forgot-password' | '/login' | '/reset-password' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forgot-password' | '/login' | '/reset-password' | '/signup'
  id:
    | '__root__'
    | '/(dashboard)'
    | '/(auth)/_layout'
    | '/(dashboard)/'
    | '/(auth)/_layout/forgot-password'
    | '/(auth)/_layout/login'
    | '/(auth)/_layout/reset-password'
    | '/(auth)/_layout/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  authLayoutRoute: typeof authLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout/signup': {
      id: '/(auth)/_layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authLayoutSignupRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/reset-password': {
      id: '/(auth)/_layout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authLayoutResetPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/login': {
      id: '/(auth)/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLayoutLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/forgot-password': {
      id: '/(auth)/_layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authLayoutForgotPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
  }
}

interface dashboardRouteRouteChildren {
  dashboardIndexRoute: typeof dashboardIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardIndexRoute: dashboardIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

interface authLayoutRouteChildren {
  authLayoutForgotPasswordRoute: typeof authLayoutForgotPasswordRoute
  authLayoutLoginRoute: typeof authLayoutLoginRoute
  authLayoutResetPasswordRoute: typeof authLayoutResetPasswordRoute
  authLayoutSignupRoute: typeof authLayoutSignupRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutForgotPasswordRoute: authLayoutForgotPasswordRoute,
  authLayoutLoginRoute: authLayoutLoginRoute,
  authLayoutResetPasswordRoute: authLayoutResetPasswordRoute,
  authLayoutSignupRoute: authLayoutSignupRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  authLayoutRoute: authLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
